apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-assistant-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website-assistant
  template:
    metadata:
      labels:
        app: website-assistant
    spec:
      containers:
      - name: website-assistant
        image: abdulkabeer1/website_assistant:latest
        ports:
        - containerPort: 8000
